services:
  eurekasystem:
    image: eurekasystem
    build: ./discavery-server/
    ports: 
      - 8761:8761

  zuulgwsystem:
    image: zuulgwsystem
    build: ./api-gateway/
    ports: 
      - 9092:9092
    links:
      - "visitsystem:visitsystem"
      - "eurekasystem:eurekasystem"
      - "user-authentication-system:user-authentication-system"

  dbusers:
    image: dbusers
    build: ./user-authentication-system/database
    environment:
      MS_SQL_PASSWORD: "Password-123"
      ACCEPT_EULA: "Y"
    volumes: 
      - ./user-authentication-system/database/dbUsersVol:/var/opt/mssql/data
    #ports:
    #  - "1435:1433"

  user-authentication-system:
    image: user-authentication-system
    build: ./user-authentication-system/
    depends_on:
      - dbusers
      - eurekasystem
    links: 
      - "dbusers:dbusers"
      - "eurekasystem:eurekasystem"

  dbvisits:
    image: dbvisits
    build: ./BookVisitSystem/database
    environment:
      MS_SQL_PASSWORD: "Password-123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./BookVisitSystem/database/dbVisitsVol:/var/opt/mssql/data
    #ports:
    #  - 1436:1433

  visitsystem:
    image: visitsystem
    build: ./BookVisitSystem/
    #ports:
    #  - 8081:8080
    depends_on:
      - dbvisits
      - eurekasystem
    links:
      - "dbvisits:dbvisits"
      - "eurekasystem:eurekasystem"
