version: '3.7'

services:

  frontapp:
    image: frontapp
    ports:
      - 4200:4200
    depends_on:
      - zuulgwsystem

  eurekasystem:
    image: eurekasystem
    ports: 
      - 8761:8761

  zuulgwsystem:
    image: zuulgwsystem
    ports: 
      - 9092:9092

  prometheus:
    image: prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes: 
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"


  dbusers:
    image: dbusers
    environment:
      MS_SQL_PASSWORD: "Password-123"
      ACCEPT_EULA: "Y"
    volumes: 
      - ./user-authentication-system/database/dbUsersVol:/var/opt/mssql/data
    ports:
      - "1435:1433"

  user-authentication-system:
    image: user-authentication-system
    ports:
      - 9093:9093
    depends_on:
      - dbusers
      - eurekasystem


  dbreminders:
    image: dbreminders
    environment:
      MS_SQL_PASSWORD: "Password-123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./VisitReminderSystem/database/dbRemindersVol:/var/opt/mssql/data
    ports:
      - 1434:1433

  reminderssystem:
    image: reminderssystem
    ports:
      - 9095:9095
    depends_on:
      - dbreminders
      - eurekasystem


  dbreceipts:
    image: dbreceipts
    environment:
      MS_SQL_PASSWORD: "Password-123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./ReceiptGeneratorSystem/database/dbMedicalsVol:/var/opt/mssql/data
    ports:
      - 1437:1433

  receiptssystem:
    image: receiptssystem
    ports:
      - 9096:9096
    depends_on:
      - dbreceipts
      - eurekasystem


  dbvisits:
    image: dbvisits
    environment:
      MS_SQL_PASSWORD: "Password-123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./BookVisitSystem/database/dbVisitsVol:/var/opt/mssql/data
    ports:
      - 1436:1433

  visitsystem:
    image: visitsystem
    ports:
      - 9094:9094
    depends_on:
      - dbvisits
      - eurekasystem
