USE [master]
GO
/****** Object:  Database [dbUsers]    Script Date: 14.11.2020 11:29:18 ******/
CREATE DATABASE [dbUsers]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'dbUsers', FILENAME = N'/var/opt/mssql/data/dbUsers.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'dbUsers_log', FILENAME = N'/var/opt/mssql/data/dbUsers_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [dbUsers] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbUsers].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dbUsers] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [dbUsers] SET ANSI_NULLS OFF
GO
ALTER DATABASE [dbUsers] SET ANSI_PADDING OFF
GO
ALTER DATABASE [dbUsers] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [dbUsers] SET ARITHABORT OFF
GO
ALTER DATABASE [dbUsers] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [dbUsers] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [dbUsers] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [dbUsers] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [dbUsers] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [dbUsers] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [dbUsers] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [dbUsers] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [dbUsers] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [dbUsers] SET  DISABLE_BROKER
GO
ALTER DATABASE [dbUsers] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [dbUsers] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [dbUsers] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [dbUsers] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [dbUsers] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [dbUsers] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [dbUsers] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [dbUsers] SET RECOVERY FULL
GO
ALTER DATABASE [dbUsers] SET  MULTI_USER
GO
ALTER DATABASE [dbUsers] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [dbUsers] SET DB_CHAINING OFF
GO
ALTER DATABASE [dbUsers] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [dbUsers] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [dbUsers] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [dbUsers] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'dbUsers', N'ON'
GO
ALTER DATABASE [dbUsers] SET QUERY_STORE = OFF
GO
USE [dbUsers]
GO
/****** Object:  Table [dbo].[Doctors]    Script Date: 14.11.2020 11:29:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Doctors](
	[id] [varchar](50) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[surname] [varchar](50) NOT NULL,
	[email] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Doctors] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DoctorSpecialization]    Script Date: 14.11.2020 11:29:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DoctorSpecialization](
	[doctorID] [varchar](50) NOT NULL,
	[specializationID] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Patients]    Script Date: 14.11.2020 11:29:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Patients](
	[id] [varchar](50) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[surname] [varchar](50) NOT NULL,
	[pesel] [varchar](50) NOT NULL,
	[email] [varchar](50) NOT NULL,
	[birthday] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Patients] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DoctorSpecialization]  WITH CHECK ADD  CONSTRAINT [FK_DoctorSpecialization_Doctors] FOREIGN KEY([doctorID])
REFERENCES [dbo].[Doctors] ([id])
GO
ALTER TABLE [dbo].[DoctorSpecialization] CHECK CONSTRAINT [FK_DoctorSpecialization_Doctors]
GO
USE [master]
GO
ALTER DATABASE [dbUsers] SET  READ_WRITE
GO
