# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
#rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'visitsystem'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
     - targets: ['visitsystem:9094']
  - job_name: 'receiptssystem'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
     - targets: ['receiptssystem:9096']
  - job_name: 'reminderssystem'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
     - targets: ['reminderssystem:9095']
  - job_name: 'user-authentication-system'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
     - targets: ['user-authentication-system:9093']
  - job_name: 'zuulgwsystem'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
     - targets: ['zuulgwsystem:9092']
  - job_name: 'eurekasystem'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
     - targets: ['eurekasystem:8761']
