USE [master]
GO
/****** Object:  Database [dbVisits]    Script Date: 14.11.2020 11:02:34 ******/
CREATE DATABASE [dbVisits]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'dbVisits', FILENAME = N'/var/opt/mssql/data/dbVisits.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'dbVisits_log', FILENAME = N'/var/opt/mssql/data/dbVisits_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [dbVisits] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbVisits].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dbVisits] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [dbVisits] SET ANSI_NULLS OFF
GO
ALTER DATABASE [dbVisits] SET ANSI_PADDING OFF
GO
ALTER DATABASE [dbVisits] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [dbVisits] SET ARITHABORT OFF
GO
ALTER DATABASE [dbVisits] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [dbVisits] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [dbVisits] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [dbVisits] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [dbVisits] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [dbVisits] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [dbVisits] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [dbVisits] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [dbVisits] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [dbVisits] SET  DISABLE_BROKER
GO
ALTER DATABASE [dbVisits] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [dbVisits] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [dbVisits] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [dbVisits] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [dbVisits] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [dbVisits] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [dbVisits] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [dbVisits] SET RECOVERY FULL
GO
ALTER DATABASE [dbVisits] SET  MULTI_USER
GO
ALTER DATABASE [dbVisits] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [dbVisits] SET DB_CHAINING OFF
GO
ALTER DATABASE [dbVisits] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [dbVisits] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [dbVisits] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [dbVisits] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'dbVisits', N'ON'
GO
ALTER DATABASE [dbVisits] SET QUERY_STORE = OFF
GO
USE [dbVisits]
GO
/****** Object:  Table [dbo].[Specializations]    Script Date: 14.11.2020 11:02:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Specializations](
	[id] [varchar](50) NOT NULL,
	[specialization] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Specializations] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Visits]    Script Date: 14.11.2020 11:02:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Visits](
	[id] [varchar](50) NOT NULL,
	[date] [datetime] NOT NULL,
	[notes] [varchar](50) NULL,
	[doctorID] [varchar](50) NOT NULL,
	[patientID] [varchar](50) NOT NULL,
	[specializationID] [varchar](50) NOT NULL,
	[medicalsID] [varchar](50) NULL,
 CONSTRAINT [PK_Visits] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Visits]    Script Date: 14.11.2020 11:02:34 ******/
CREATE NONCLUSTERED INDEX [IX_Visits] ON [dbo].[Visits]
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Visits]  WITH CHECK ADD  CONSTRAINT [FK_Visits_Specializations] FOREIGN KEY([specializationID])
REFERENCES [dbo].[Specializations] ([id])
GO
ALTER TABLE [dbo].[Visits] CHECK CONSTRAINT [FK_Visits_Specializations]
GO
USE [master]
GO
ALTER DATABASE [dbVisits] SET  READ_WRITE
GO
