USE [master]
GO
/****** Object:  Database [dbReceipts]    Script Date: 16.11.2020 22:57:20 ******/
CREATE DATABASE [dbReceipts]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'dbReceipts', FILENAME = N'/var/opt/mssql/data/dbReceipts.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'dbReceipts_log', FILENAME = N'/var/opt/mssql/data/dbReceipts_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [dbReceipts] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbReceipts].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dbReceipts] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [dbReceipts] SET ANSI_NULLS OFF
GO
ALTER DATABASE [dbReceipts] SET ANSI_PADDING OFF
GO
ALTER DATABASE [dbReceipts] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [dbReceipts] SET ARITHABORT OFF
GO
ALTER DATABASE [dbReceipts] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [dbReceipts] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [dbReceipts] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [dbReceipts] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [dbReceipts] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [dbReceipts] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [dbReceipts] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [dbReceipts] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [dbReceipts] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [dbReceipts] SET  DISABLE_BROKER
GO
ALTER DATABASE [dbReceipts] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [dbReceipts] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [dbReceipts] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [dbReceipts] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [dbReceipts] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [dbReceipts] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [dbReceipts] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [dbReceipts] SET RECOVERY FULL
GO
ALTER DATABASE [dbReceipts] SET  MULTI_USER
GO
ALTER DATABASE [dbReceipts] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [dbReceipts] SET DB_CHAINING OFF
GO
ALTER DATABASE [dbReceipts] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [dbReceipts] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [dbReceipts] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [dbReceipts] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'dbReceipts', N'ON'
GO
ALTER DATABASE [dbReceipts] SET QUERY_STORE = OFF
GO
USE [dbReceipts]
GO
/****** Object:  Table [dbo].[Medicals]    Script Date: 16.11.2020 22:57:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Medicals](
	[id] [varchar](50) NOT NULL,
	[name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Medicals] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ReceiptMedicals]    Script Date: 16.11.2020 22:57:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ReceiptMedicals](
	[receiptID] [varchar](50) NOT NULL,
	[medicalsID] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Receipts]    Script Date: 16.11.2020 22:57:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Receipts](
	[id] [varchar](50) NOT NULL,
	[patientID] [varchar](50) NOT NULL,
	[doctorID] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Receipts] PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ReceiptMedicals]  WITH CHECK ADD  CONSTRAINT [FK_ReceiptMedicals_Medicals] FOREIGN KEY([medicalsID])
REFERENCES [dbo].[Medicals] ([id])
GO
ALTER TABLE [dbo].[ReceiptMedicals] CHECK CONSTRAINT [FK_ReceiptMedicals_Medicals]
GO
ALTER TABLE [dbo].[ReceiptMedicals]  WITH CHECK ADD  CONSTRAINT [FK_ReceiptMedicals_Receipts] FOREIGN KEY([receiptID])
REFERENCES [dbo].[Receipts] ([id])
GO
ALTER TABLE [dbo].[ReceiptMedicals] CHECK CONSTRAINT [FK_ReceiptMedicals_Receipts]
GO
USE [master]
GO
ALTER DATABASE [dbReceipts] SET  READ_WRITE
GO
